[opener]
edit = [{ run = 'yazi-edit "$1"' }]

[open]
prepend_rules = [
  { name = "*/", use = [
    "edit",
  ] },
  { mime = "text/*", use = [
    "edit",
  ] },
]

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"
