[opener]
edit = [{ run = 'yazi-pick args "$@"', desc = "edit" }]
hsplit = [{ run = 'yazi-pick hsplit $1', desc = "hsplit" }]

[open]
prepend_rules = [{ mime = "text/*", use = ["edit", "hsplit", "vsplit"] }]

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"
